// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwvus8mAtZ8Ua6_mWuk78zsxKNOzFPpPc',
    appId: '1:196032750035:web:3811b60982c1c2f5c44f26',
    messagingSenderId: '196032750035',
    projectId: 'queueless-fcm',
    authDomain: 'queueless-fcm.firebaseapp.com',
    storageBucket: 'queueless-fcm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkkviwyWW9PIjAUdP8yVAJO1gbNo8DB5Y',
    appId: '1:196032750035:android:17d30fde5a30f050c44f26',
    messagingSenderId: '196032750035',
    projectId: 'queueless-fcm',
    storageBucket: 'queueless-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcauJvLBgMOqOQujxsg_B8SAaN56n0Dq0',
    appId: '1:196032750035:ios:18b864cc612d1be1c44f26',
    messagingSenderId: '196032750035',
    projectId: 'queueless-fcm',
    storageBucket: 'queueless-fcm.firebasestorage.app',
    iosBundleId: 'com.example.queueless',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcauJvLBgMOqOQujxsg_B8SAaN56n0Dq0',
    appId: '1:196032750035:ios:18b864cc612d1be1c44f26',
    messagingSenderId: '196032750035',
    projectId: 'queueless-fcm',
    storageBucket: 'queueless-fcm.firebasestorage.app',
    iosBundleId: 'com.example.queueless',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwvus8mAtZ8Ua6_mWuk78zsxKNOzFPpPc',
    appId: '1:196032750035:web:c42569acaf204605c44f26',
    messagingSenderId: '196032750035',
    projectId: 'queueless-fcm',
    authDomain: 'queueless-fcm.firebaseapp.com',
    storageBucket: 'queueless-fcm.firebasestorage.app',
  );
}
